version: '3.8'

services:
  mongo:
    image: mongo:6
    restart: always
    ports:
      - "27018:27017"
    volumes:
      - mongo-data:/data/db
    networks:
      - breava-net

  mongo-express:
    image: mongo-express
    restart: always
    ports:
      - "8082:8081"
    environment:
      ME_CONFIG_MONGODB_SERVER: mongo
      ME_CONFIG_MONGODB_URL: "mongodb://mongo:27017/Breava"
    depends_on:
      - mongo
    networks:
      - breava-net

  server:
    build:
      context: ./server
    image: breava-capstone-server
    restart: always
    env_file:
      - .env
    # fallback in case you still want to override via compose
    environment:
      - MONGO_URI=mongodb://mongo:27017/Breava
    command: flask run --host=0.0.0.0 --port=5000
    ports:
      - "5000:5000"
    depends_on:
      - mongo
    networks:
      - breava-net

  client:
    build:
      context: ./client
    image: breava-capstone-client
    restart: always
    ports:
      - "3000:3000"
    environment:
      - REACT_APP_API_URL=http://localhost:5000
    depends_on:
      - server
    networks:
      - breava-net

  ml-service:
    build:
      context: ./ml_service
      dockerfile: Dockerfile
    image: breava-capstone-ml-service
    restart: always
    env_file:
      - .env
    environment:
      - MONGO_URI=mongodb://mongo:27017/Breava
    command: flask run --host=0.0.0.0 --port=8008
    ports:
      - "8008:8008"
    depends_on:
      - mongo
    networks:
      - breava-net

volumes:
  mongo-data:

networks:
  breava-net:
    driver: bridge