version: '3.8'

services:
  mongo:
    image: mongo:6
    container_name: mongo-container
    ports:
      - "27018:27017"
    volumes:
      - mongo-data:/data/db
    networks:
      - breava-net

  mongo-express:
    image: mongo-express
    container_name: mongo-express-container
    ports:
      - "8082:8081"
    environment:
      - ME_CONFIG_MONGODB_SERVER=mongo
    depends_on:
      - mongo
    networks:
      - breava-net

  server:
    image: breava-capstone-server
    container_name: breava-capstone-server
    ports:
      - "5000:5000"
    environment:
      - MONGO_URI=mongodb://mongo:27017/Breava
    depends_on:
      - mongo
    networks:
      - breava-net

  client:
    image: breava-capstone-client
    container_name: breava-capstone-client
    ports:
      - "3000:3000"
    depends_on:
      - server
    networks:
      - breava-net

volumes:
  mongo-data:

networks:
  breava-net:
    driver: bridge
