version: '3.8'

services:
  mongo:
    image: mongo:6
    ports:
      - "27018:27017"
    volumes:
      - mongo-data:/data/db
    networks:
      - breava-net

  mongo-express:
    image: mongo-express
    ports:
      - "8082:8081"
    environment:
      - ME_CONFIG_MONGODB_SERVER=mongo
    depends_on:
      - mongo
    networks:
      - breava-net

  server:
    image: breava-capstone-server
    build:
      context: ./server
    ports:
      - "5000:5000"
    environment:
      - MONGO_URI=mongodb://mongo:27017/Breava
      - JWT_SECRET=breava_secretkey22
      - PORT=5000
      - FLASK_URL=http://ml-service:8008
    depends_on:
      - mongo
      - ml-service
    networks:
      - breava-net

  client:
    image: breava-capstone-client
    build:
      context: ./client
    ports:
      - "3000:3000"
    depends_on:
      - server
    networks:
      - breava-net

  ml-service:
    build:
      context: ./ml_service
      dockerfile: Dockerfile
    ports:
      - "8008:8008"
    depends_on:
      - mongo
    networks:
      - breava-net

volumes:
  mongo-data:

networks:
  breava-net:
    driver: bridge